In [42]:
%matplotlib inline
import numpy as np
from scipy.stats import multivariate_normal


k = 3 # Number of observables 

mu = [0]*k
Sigma=[[1,0.5,0],
       [0.5,2,0],
       [0,0,3]]

T = multivariate_normal(mu,Sigma) 

u = multivariate_normal(cov=0.2) 

In [43]:
beta = [1/2,1] # list of (1,2) and (1)

D = np.random.random(size=(3,2)) # Generate random 3x2 matrix

N=1000 # Sample size

# Now: Transform rvs into a sample
T = T.rvs(N) # sample of N draws

u = u.rvs(N) # Replace u with a sample

X = (T**3)@D  # Note use of ** operator for exponentiation

y = X@beta + u # Note use of @ operator for matrix multiplication

In [40]:
from scipy.linalg import inv, sqrtm

# we solve for b where T.T@X@b = T.T@y
b = np.linalg.lstsq(T.T@X,T.T@y)[0] # lstsqs returns several results
# np.linalg.lstsq: Returns least-square sol'n for linear matrix eq

e = y - X@b

print(b)

TXplus = np.linalg.pinv(T.T@X) # Moore-Penrose pseudo-inverse

# Covariance matrix of b
vb = e.var()*TXplus@T.T@T@TXplus.T  # u is known to be homoskedastic

print(vb)

[0.50006212 1.00060333]
[[ 4.32976958e-04 -1.63770872e-04]
 [-1.63770872e-04  6.51337626e-05]]


/tmp/ipykernel_30/448000770.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  b = np.linalg.lstsq(T.T@X,T.T@y)[0] # lstsqs returns several results


In [45]:
# Task: Extend the code in weighted_regression.ipynb to actually estimate β in the case with k = 3.
# To solve for b, we had T'y = T'Xb + T'u with the assumption that E(T'u)=0
# We know that X=T^3*D
# Then to solve for b, we have T'y = T'T^{3}Db

k=3 
print("Sigma", Sigma)
print(np.shape(Sigma))



T_cube = T**3 
# print(T_cube)
# b = (T'T^{3}D)^-1 * (T'y)
D = np.random.random(size=(3,3)) # D is a l x k matrix, so now the size needs to change from before  (it was 3x2 above)

first = (T.T@T_cube@D)
second = T.T@y


b_k3= np.linalg.inv(first)@second

print(b_k3)

# Can check with another way to estimate b: 
b_3 = np.linalg.lstsq(first,second)[0] 
print(b_k3)

Sigma [[1, 0.5, 0], [0.5, 2, 0], [0, 0, 3]]
(3, 3)
[-1.721916    1.02741119  3.89706085]
[-1.721916    1.02741119  3.89706085]


/tmp/ipykernel_30/1928341346.py:26: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  b_3 = np.linalg.lstsq(first,second)[0]
